In [9]:
# filename=r"C:\Users\25004\Desktop\t_exam_paper_answer.csv"
# 表头 
filename=r"C:\Users\25004\Desktop\t_exam_paper_answer(2).csv"

1 pip install -i https://pypi.tuna.tsinghua.edu.cn/simple some-package

pip install -i https://pypi.tuna.tsinghua.edu.cn/simple   notebook

D:\software\anaconda\envs\py374\Scripts jupyter notebook D:\proj\python\my_util_py_pub\record.py

In [4]:
!pip install pyspark -i https://pypi.tuna.tsinghua.edu.cn/simple

Collecting pyspark
  Downloading pyspark-3.3.1.tar.gz (281.4 MB)
     -------------------------------------- 281.4/281.4 MB 1.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting py4j==0.10.9.5
  Downloading py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)
     ------------------------------------ 199.7/199.7 kB 485.9 kB/s eta 0:00:00
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py): started
  Building wheel for pyspark (setup.py): finished with status 'done'
  Created wheel for pyspark: filename=pyspark-3.3.1-py2.py3-none-any.whl size=281845525 sha256=8fe760171ef733e7191a9adb01da12c5f0655ac6d8fe15c68bf7501493d4726c
  Stored in directory: c:\users\25004\appdata\local\pip\cache\wheels\42\59\f5\79a5bf931714dcd201b26025347785f087370a10a3329a899c
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.5 pyspark-3.3.1

In [5]:
from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .enableHiveSupport().getOrCreate()
# df = spark.read.csv(filename)
# df.printSchema()
##可以得到
# root
#  |-- _c0: string (nullable = true)
#  |-- _c1: string (nullable = true)
#  |-- _c2: string (nullable = true)

root
 |-- _c0: string (nullable = true)
 |-- _c1: string (nullable = true)
 |-- _c2: string (nullable = true)
 |-- _c3: string (nullable = true)
 |-- _c4: string (nullable = true)
 |-- _c5: string (nullable = true)
 |-- _c6: string (nullable = true)
 |-- _c7: string (nullable = true)
 |-- _c8: string (nullable = true)
 |-- _c9: string (nullable = true)
 |-- _c10: string (nullable = true)
 |-- _c11: string (nullable = true)
 |-- _c12: string (nullable = true)
 |-- _c13: string (nullable = true)
 |-- _c14: string (nullable = true)

In [12]:
df = spark.read.csv(filename,header=True)
df.printSchema()

root
 |-- id: string (nullable = true)
 |-- exam_paper_id: string (nullable = true)
 |-- paper_name: string (nullable = true)
 |-- paper_type: string (nullable = true)
 |-- subject_id: string (nullable = true)
 |-- system_score: string (nullable = true)
 |-- user_score: string (nullable = true)
 |-- paper_score: string (nullable = true)
 |-- question_correct: string (nullable = true)
 |-- question_count: string (nullable = true)
 |-- do_time: string (nullable = true)
 |-- status: string (nullable = true)
 |-- create_user: string (nullable = true)
 |-- create_time: string (nullable = true)
 |-- task_exam_id: string (nullable = true)

ModuleNotFoundError: No module named 'pyspark'

In [7]:
!pip install pandas -i https://pypi.tuna.tsinghua.edu.cn/simple

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pandas
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b2/56/f886ed6f1777ffa9d54c6e80231b69db8a1f52dcc33f5967b06a105dcfe0/pandas-1.3.5-cp37-cp37m-win_amd64.whl (10.0 MB)
Requirement already satisfied: numpy>=1.17.3 in d:\software\anaconda\envs\py374\lib\site-packages (from pandas) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in d:\software\anaconda\envs\py374\lib\site-packages (from pandas) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.7.3 in d:\software\anaconda\envs\py374\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in d:\software\anaconda\envs\py374\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Installing collected packages: pandas
Successfully installed pandas-1.3.5

In [13]:
df.toPandas()

,id,exam_paper_id,paper_name,paper_type,subject_id,system_score,user_score,paper_score,question_correct,question_count,do_time,status,create_user,create_time,task_exam_id
0,1,12,java基础知识测试（一）,1,4,100,100,180,3,6,64,2,6,2021/4/26 11:13:07,None
1,2,13,Java基础知识测试（二）,1,4,40,40,80,3,5,15,2,6,2021/4/26 13:24:02,None
2,3,14,java基础知识测试（三）,1,4,0,50,50,2,2,89,2,6,2021/4/26 13:31:15,None
3,4,15,智能试卷1,8,4,30,80,100,3,4,60,2,6,2021/4/26 14:24:14,None
4,5,29,智能训练1,8,4,0,0,140,0,6,8,2,6,2021/4/27 19:52:41,None
5,6,13,Java基础知识测试（二）,1,4,50,50,80,3,5,59,2,6,2021/5/3 21:16:12,None
6,7,45,智能试卷1,10,4,20,50,350,3,12,18,2,6,2021/5/4 16:02:18,None
7,8,55,智能试卷7,10,4,20,80,350,1,12,17,2,6,2021/5/7 23:56:39,None
8,9,46,智能训练1,8,4,0,20,230,0,8,23,2,6,2021/5/11 00:35:11,None
9,10,79,智能训练2,8,4,20,100,210,1,5,8,2,6,2021/5/15 09:41:48,None
10,11,82,智能训练4,8,4,20,60,90,3,5,13,2,6,2021/5/15 09:45:44,None
11,12,89,智能训练10,8,4,0,100,110,2,3,6,2,6,2021/5/15 09:53:13,None
12,13,92,智能训练12,8,4,10,30,50,2,3,6,2,6,2021/5/15 09:56:34,None
13,14,94,智能试卷1,10,4,30,140,350,2,12,17,2,6,2021/5/21 23:14:45,None
14,15,95,java,1,3,10,10,10,1,1,1,2,8,2022/6/20 12:50:05,None
15,16,95,java,1,3,10,10,10,1,1,8,2,6,2022/7/7 10:58:40,None
16,17,95,java,1,3,10,10,10,1,1,1,2,8,2022/7/7 12:54:27,None
17,18,95,java,1,3,0,0,10,0,1,1200,2,8,2022/7/7 13:35:11,None
18,19,95,java,1,3,10,10,10,1,1,2,2,6,2022/7/12 13:48:49,None
19,20,95,java,1,3,0,0,10,0,1,2,2,6,2022/7/12 13:50:31,None
20,21,95,java,1,3,10,10,10,1,1,15,2,6,2022/10/20 19:59:37,None
21,22,95,java,1,3,10,10,10,1,1,172,2,6,2022/10/20 20:07:34,None
22,23,96,面经 前端,1,15,0,0,10,0,1,3,1,6,2022/10/20 20:51:10,None
23,24,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 16:43:27,None
24,25,95,java,1,3,0,0,10,0,1,2,2,6,2022/10/22 16:44:29,None
25,26,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 17:11:29,None
26,27,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 17:14:07,None
27,28,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 17:15:38,None
28,29,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 18:50:18,None
29,30,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 18:52:41,None
30,31,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 19:16:31,None

最终得分(千分制)
根据 排名 pyspark 
pyspark 分组排序，按分区内的排序标上序号_sijin_190527的博客-CSDN博客_pyspark 分组排序
https://blog.csdn.net/sijin_190527/article/details/121754087

import

from py

In [ ]:
from pyspark import copy_func
from pyspark import func

In [14]:
from pyspark.sql import functions as F

In [16]:
from pyspark.sql.window import Window
 
window = Window.partitionBy('exam_paper_id').orderBy(df.user_score.desc())
df_top_n = df.withColumn('top_n', F.rank().over(window))
 
 
#group是分组字段
#count是排序字段
#topn是新增字段，用来存储排序序号

AnalysisException: Column 'group' does not exist. Did you mean one of the following? [

In [17]:
df_top_n.toPandas()

,id,exam_paper_id,paper_name,paper_type,subject_id,system_score,user_score,paper_score,question_correct,question_count,do_time,status,create_user,create_time,task_exam_id,top_n
0,1,12,java基础知识测试（一）,1,4,100,100,180,3,6,64,2,6,2021/4/26 11:13:07,None,1
1,6,13,Java基础知识测试（二）,1,4,50,50,80,3,5,59,2,6,2021/5/3 21:16:12,None,1
2,2,13,Java基础知识测试（二）,1,4,40,40,80,3,5,15,2,6,2021/4/26 13:24:02,None,2
3,3,14,java基础知识测试（三）,1,4,0,50,50,2,2,89,2,6,2021/4/26 13:31:15,None,1
4,4,15,智能试卷1,8,4,30,80,100,3,4,60,2,6,2021/4/26 14:24:14,None,1
5,5,29,智能训练1,8,4,0,0,140,0,6,8,2,6,2021/4/27 19:52:41,None,1
6,7,45,智能试卷1,10,4,20,50,350,3,12,18,2,6,2021/5/4 16:02:18,None,1
7,9,46,智能训练1,8,4,0,20,230,0,8,23,2,6,2021/5/11 00:35:11,None,1
8,8,55,智能试卷7,10,4,20,80,350,1,12,17,2,6,2021/5/7 23:56:39,None,1
9,10,79,智能训练2,8,4,20,100,210,1,5,8,2,6,2021/5/15 09:41:48,None,1
10,11,82,智能训练4,8,4,20,60,90,3,5,13,2,6,2021/5/15 09:45:44,None,1
11,12,89,智能训练10,8,4,0,100,110,2,3,6,2,6,2021/5/15 09:53:13,None,1
12,13,92,智能训练12,8,4,10,30,50,2,3,6,2,6,2021/5/15 09:56:34,None,1
13,14,94,智能试卷1,10,4,30,140,350,2,12,17,2,6,2021/5/21 23:14:45,None,1
14,15,95,java,1,3,10,10,10,1,1,1,2,8,2022/6/20 12:50:05,None,1
15,16,95,java,1,3,10,10,10,1,1,8,2,6,2022/7/7 10:58:40,None,1
16,17,95,java,1,3,10,10,10,1,1,1,2,8,2022/7/7 12:54:27,None,1
17,19,95,java,1,3,10,10,10,1,1,2,2,6,2022/7/12 13:48:49,None,1
18,21,95,java,1,3,10,10,10,1,1,15,2,6,2022/10/20 19:59:37,None,1
19,22,95,java,1,3,10,10,10,1,1,172,2,6,2022/10/20 20:07:34,None,1
20,18,95,java,1,3,0,0,10,0,1,1200,2,8,2022/7/7 13:35:11,None,7
21,20,95,java,1,3,0,0,10,0,1,2,2,6,2022/7/12 13:50:31,None,7
22,25,95,java,1,3,0,0,10,0,1,2,2,6,2022/10/22 16:44:29,None,7
23,23,96,面经 前端,1,15,0,0,10,0,1,3,1,6,2022/10/20 20:51:10,None,1
24,24,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 16:43:27,None,1
25,26,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 17:11:29,None,1
26,27,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 17:14:07,None,1
27,28,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 17:15:38,None,1
28,29,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 18:50:18,None,1
29,30,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 18:52:41,None,1
30,31,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 19:16:31,None,1

In [20]:
df_top_n.columns

['id',
 'exam_paper_id',
 'paper_name',
 'paper_type',
 'subject_id',
 'system_score',
 'user_score',
 'paper_score',
 'question_correct',
 'question_count',
 'do_time',
 'status',
 'create_user',
 'create_time',
 'task_exam_id',
 'top_n']

In [ ]:
ImportError: Pandas >= 1.0.5 must be installed; however, it was not found.

In [19]:
df_top_n.select(df_top_n.top_n,"paper_name","user_score","create_user").toPandas()

    top_n     paper_name user_score create_user
0       1  java基础知识测试（一）        100           6
1       1  Java基础知识测试（二）         50           6
2       2  Java基础知识测试（二）         40           6
3       1  java基础知识测试（三）         50           6
4       1          智能试卷1         80           6
5       1          智能训练1          0           6
6       1          智能试卷1         50           6
7       1          智能训练1         20           6
8       1          智能试卷7         80           6
9       1          智能训练2        100           6
10      1          智能训练4         60           6
11      1         智能训练10        100           6
12      1         智能训练12         30           6
13      1          智能试卷1        140           6
14      1           java         10           8
15      1           java         10           6
16      1           java         10           8
17      1           java         10           6
18      1           java         10           6
19      1           java         10           6
20      7           java          0           8
21      7           java          0           6
22      7           java          0           6
23      1          面经 前端          0           6
24      1          面经 前端          0           6
25      1          面经 前端          0           6
26      1          面经 前端          0           6
27      1          面经 前端          0           6
28      1          面经 前端          0           6
29      1          面经 前端          0           6
30      1          面经 前端          0           6

In [21]:
df_top_n.select(df_top_n.top_n,"paper_name","user_score","create_user","paper_score").toPandas()

    top_n     paper_name user_score create_user paper_score
0       1  java基础知识测试（一）        100           6         180
1       1  Java基础知识测试（二）         50           6          80
2       2  Java基础知识测试（二）         40           6          80
3       1  java基础知识测试（三）         50           6          50
4       1          智能试卷1         80           6         100
5       1          智能训练1          0           6         140
6       1          智能试卷1         50           6         350
7       1          智能训练1         20           6         230
8       1          智能试卷7         80           6         350
9       1          智能训练2        100           6         210
10      1          智能训练4         60           6          90
11      1         智能训练10        100           6         110
12      1         智能训练12         30           6          50
13      1          智能试卷1        140           6         350
14      1           java         10           8          10
15      1           java         10           6          10
16      1           java         10           8          10
17      1           java         10           6          10
18      1           java         10           6          10
19      1           java         10           6          10
20      7           java          0           8          10
21      7           java          0           6          10
22      7           java          0           6          10
23      1          面经 前端          0           6          10
24      1          面经 前端          0           6          10
25      1          面经 前端          0           6          10
26      1          面经 前端          0           6          10
27      1          面经 前端          0           6          10
28      1          面经 前端          0           6          10
29      1          面经 前端          0           6          10
30      1          面经 前端          0           6          10

In [22]:
df_top_n.withColumn("score_percent",F.col("user_score")/F.col("paper_score")).toPandas()

,id,exam_paper_id,paper_name,paper_type,subject_id,system_score,user_score,paper_score,question_correct,question_count,do_time,status,create_user,create_time,task_exam_id,top_n,score_percent
0,1,12,java基础知识测试（一）,1,4,100,100,180,3,6,64,2,6,2021/4/26 11:13:07,None,1,0.555556
1,6,13,Java基础知识测试（二）,1,4,50,50,80,3,5,59,2,6,2021/5/3 21:16:12,None,1,0.625000
2,2,13,Java基础知识测试（二）,1,4,40,40,80,3,5,15,2,6,2021/4/26 13:24:02,None,2,0.500000
3,3,14,java基础知识测试（三）,1,4,0,50,50,2,2,89,2,6,2021/4/26 13:31:15,None,1,1.000000
4,4,15,智能试卷1,8,4,30,80,100,3,4,60,2,6,2021/4/26 14:24:14,None,1,0.800000
5,5,29,智能训练1,8,4,0,0,140,0,6,8,2,6,2021/4/27 19:52:41,None,1,0.000000
6,7,45,智能试卷1,10,4,20,50,350,3,12,18,2,6,2021/5/4 16:02:18,None,1,0.142857
7,9,46,智能训练1,8,4,0,20,230,0,8,23,2,6,2021/5/11 00:35:11,None,1,0.086957
8,8,55,智能试卷7,10,4,20,80,350,1,12,17,2,6,2021/5/7 23:56:39,None,1,0.228571
9,10,79,智能训练2,8,4,20,100,210,1,5,8,2,6,2021/5/15 09:41:48,None,1,0.476190
10,11,82,智能训练4,8,4,20,60,90,3,5,13,2,6,2021/5/15 09:45:44,None,1,0.666667
11,12,89,智能训练10,8,4,0,100,110,2,3,6,2,6,2021/5/15 09:53:13,None,1,0.909091
12,13,92,智能训练12,8,4,10,30,50,2,3,6,2,6,2021/5/15 09:56:34,None,1,0.600000
13,14,94,智能试卷1,10,4,30,140,350,2,12,17,2,6,2021/5/21 23:14:45,None,1,0.400000
14,15,95,java,1,3,10,10,10,1,1,1,2,8,2022/6/20 12:50:05,None,1,1.000000
15,16,95,java,1,3,10,10,10,1,1,8,2,6,2022/7/7 10:58:40,None,1,1.000000
16,17,95,java,1,3,10,10,10,1,1,1,2,8,2022/7/7 12:54:27,None,1,1.000000
17,19,95,java,1,3,10,10,10,1,1,2,2,6,2022/7/12 13:48:49,None,1,1.000000
18,21,95,java,1,3,10,10,10,1,1,15,2,6,2022/10/20 19:59:37,None,1,1.000000
19,22,95,java,1,3,10,10,10,1,1,172,2,6,2022/10/20 20:07:34,None,1,1.000000
20,18,95,java,1,3,0,0,10,0,1,1200,2,8,2022/7/7 13:35:11,None,7,0.000000
21,20,95,java,1,3,0,0,10,0,1,2,2,6,2022/7/12 13:50:31,None,7,0.000000
22,25,95,java,1,3,0,0,10,0,1,2,2,6,2022/10/22 16:44:29,None,7,0.000000
23,23,96,面经 前端,1,15,0,0,10,0,1,3,1,6,2022/10/20 20:51:10,None,1,0.000000
24,24,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 16:43:27,None,1,0.000000
25,26,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 17:11:29,None,1,0.000000
26,27,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 17:14:07,None,1,0.000000
27,28,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 17:15:38,None,1,0.000000
28,29,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 18:50:18,None,1,0.000000
29,30,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 18:52:41,None,1,0.000000
30,31,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 19:16:31,None,1,0.000000

In [26]:
df_top_n=df_top_n.withColumn("score_percent",F.col("user_score")/F.col("paper_score")*100)

In [30]:
def get_percent():
    # F.round((F.col('Month_start')/F.col('Month_end'))*100,2))
    _100=(F.col("user_score")/F.col("paper_score"))*100
    return F.round(_100,2)

In [31]:
df_top_n=df_top_n.withColumn("score_percent",get_percent)

TypeError: col should be Column

In [32]:
df_top_n=df_top_n.withColumn("score_percent",F.round((F.col("user_score")/F.col("paper_score"))*100,2))

F.round 可以单独写一个函数

In [ ]:
from pyspark.sql.functions import col, udf

In [ ]:
convertUDF = udf(lambda z: convertCase(z))

In [ ]:
convertUDF = udf(lambda z: get_percent(z))

In [33]:
df_top_n.toPandas()

,id,exam_paper_id,paper_name,paper_type,subject_id,system_score,user_score,paper_score,question_correct,question_count,do_time,status,create_user,create_time,task_exam_id,top_n,score_percent
0,1,12,java基础知识测试（一）,1,4,100,100,180,3,6,64,2,6,2021/4/26 11:13:07,None,1,55.56
1,6,13,Java基础知识测试（二）,1,4,50,50,80,3,5,59,2,6,2021/5/3 21:16:12,None,1,62.50
2,2,13,Java基础知识测试（二）,1,4,40,40,80,3,5,15,2,6,2021/4/26 13:24:02,None,2,50.00
3,3,14,java基础知识测试（三）,1,4,0,50,50,2,2,89,2,6,2021/4/26 13:31:15,None,1,100.00
4,4,15,智能试卷1,8,4,30,80,100,3,4,60,2,6,2021/4/26 14:24:14,None,1,80.00
5,5,29,智能训练1,8,4,0,0,140,0,6,8,2,6,2021/4/27 19:52:41,None,1,0.00
6,7,45,智能试卷1,10,4,20,50,350,3,12,18,2,6,2021/5/4 16:02:18,None,1,14.29
7,9,46,智能训练1,8,4,0,20,230,0,8,23,2,6,2021/5/11 00:35:11,None,1,8.70
8,8,55,智能试卷7,10,4,20,80,350,1,12,17,2,6,2021/5/7 23:56:39,None,1,22.86
9,10,79,智能训练2,8,4,20,100,210,1,5,8,2,6,2021/5/15 09:41:48,None,1,47.62
10,11,82,智能训练4,8,4,20,60,90,3,5,13,2,6,2021/5/15 09:45:44,None,1,66.67
11,12,89,智能训练10,8,4,0,100,110,2,3,6,2,6,2021/5/15 09:53:13,None,1,90.91
12,13,92,智能训练12,8,4,10,30,50,2,3,6,2,6,2021/5/15 09:56:34,None,1,60.00
13,14,94,智能试卷1,10,4,30,140,350,2,12,17,2,6,2021/5/21 23:14:45,None,1,40.00
14,15,95,java,1,3,10,10,10,1,1,1,2,8,2022/6/20 12:50:05,None,1,100.00
15,16,95,java,1,3,10,10,10,1,1,8,2,6,2022/7/7 10:58:40,None,1,100.00
16,17,95,java,1,3,10,10,10,1,1,1,2,8,2022/7/7 12:54:27,None,1,100.00
17,19,95,java,1,3,10,10,10,1,1,2,2,6,2022/7/12 13:48:49,None,1,100.00
18,21,95,java,1,3,10,10,10,1,1,15,2,6,2022/10/20 19:59:37,None,1,100.00
19,22,95,java,1,3,10,10,10,1,1,172,2,6,2022/10/20 20:07:34,None,1,100.00
20,18,95,java,1,3,0,0,10,0,1,1200,2,8,2022/7/7 13:35:11,None,7,0.00
21,20,95,java,1,3,0,0,10,0,1,2,2,6,2022/7/12 13:50:31,None,7,0.00
22,25,95,java,1,3,0,0,10,0,1,2,2,6,2022/10/22 16:44:29,None,7,0.00
23,23,96,面经 前端,1,15,0,0,10,0,1,3,1,6,2022/10/20 20:51:10,None,1,0.00
24,24,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 16:43:27,None,1,0.00
25,26,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 17:11:29,None,1,0.00
26,27,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 17:14:07,None,1,0.00
27,28,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 17:15:38,None,1,0.00
28,29,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 18:50:18,None,1,0.00
29,30,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 18:52:41,None,1,0.00
30,31,96,面经 前端,1,15,0,0,10,0,1,60,1,6,2022/10/22 19:16:31,None,1,0.00

In [35]:
df_top_n.select(df_top_n.top_n,"paper_name","user_score","create_user","paper_score","score_percent").toPandas()

    top_n     paper_name user_score create_user paper_score  score_percent
0       1  java基础知识测试（一）        100           6         180          55.56
1       1  Java基础知识测试（二）         50           6          80          62.50
2       2  Java基础知识测试（二）         40           6          80          50.00
3       1  java基础知识测试（三）         50           6          50         100.00
4       1          智能试卷1         80           6         100          80.00
5       1          智能训练1          0           6         140           0.00
6       1          智能试卷1         50           6         350          14.29
7       1          智能训练1         20           6         230           8.70
8       1          智能试卷7         80           6         350          22.86
9       1          智能训练2        100           6         210          47.62
10      1          智能训练4         60           6          90          66.67
11      1         智能训练10        100           6         110          90.91
12      1         智能训练12         30           6          50          60.00
13      1          智能试卷1        140           6         350          40.00
14      1           java         10           8          10         100.00
15      1           java         10           6          10         100.00
16      1           java         10           8          10         100.00
17      1           java         10           6          10         100.00
18      1           java         10           6          10         100.00
19      1           java         10           6          10         100.00
20      7           java          0           8          10           0.00
21      7           java          0           6          10           0.00
22      7           java          0           6          10           0.00
23      1          面经 前端          0           6          10           0.00
24      1          面经 前端          0           6          10           0.00
25      1          面经 前端          0           6          10           0.00
26      1          面经 前端          0           6          10           0.00
27      1          面经 前端          0           6          10           0.00
28      1          面经 前端          0           6          10           0.00
29      1          面经 前端          0           6          10           0.00
30      1          面经 前端          0           6          10           0.00

TypeError: col should be Column
断言错误：col应该是Column - 问答 - Python中文网
https://www.cnpython.com/qa/44335

pyspark 保留2位小数

In [27]:
df_top_n.select(df_top_n.top_n,"paper_name","user_score","create_user","paper_score","score_percent").toPandas()

    top_n     paper_name user_score create_user paper_score  score_percent
0       1  java基础知识测试（一）        100           6         180      55.555556
1       1  Java基础知识测试（二）         50           6          80      62.500000
2       2  Java基础知识测试（二）         40           6          80      50.000000
3       1  java基础知识测试（三）         50           6          50     100.000000
4       1          智能试卷1         80           6         100      80.000000
5       1          智能训练1          0           6         140       0.000000
6       1          智能试卷1         50           6         350      14.285714
7       1          智能训练1         20           6         230       8.695652
8       1          智能试卷7         80           6         350      22.857143
9       1          智能训练2        100           6         210      47.619048
10      1          智能训练4         60           6          90      66.666667
11      1         智能训练10        100           6         110      90.909091
12      1         智能训练12         30           6          50      60.000000
13      1          智能试卷1        140           6         350      40.000000
14      1           java         10           8          10     100.000000
15      1           java         10           6          10     100.000000
16      1           java         10           8          10     100.000000
17      1           java         10           6          10     100.000000
18      1           java         10           6          10     100.000000
19      1           java         10           6          10     100.000000
20      7           java          0           8          10       0.000000
21      7           java          0           6          10       0.000000
22      7           java          0           6          10       0.000000
23      1          面经 前端          0           6          10       0.000000
24      1          面经 前端          0           6          10       0.000000
25      1          面经 前端          0           6          10       0.000000
26      1          面经 前端          0           6          10       0.000000
27      1          面经 前端          0           6          10       0.000000
28      1          面经 前端          0           6          10       0.000000
29      1          面经 前端          0           6          10       0.000000
30      1          面经 前端          0           6          10       0.000000

pyspark 转化为百分之

pyspark 只是 显示几列
如何在PySpark中只打印某一列DataFrame？ |
https://qa.1r1g.com/sf/ask/2513945451/

In [ ]:
如何在PySpark中只打印某一列DataFrame？ |
https://qa.1r1g.com/sf/ask/2513945451/

ImportError: Pandas >= 1.0.5 must be installed; however, it was not found.

In [ ]:
# data = spark.read
#     .option("inferSchema","true")#自动推导数据类型
#     .option("header","true")#读取列名
#     .csv("/user/root/image.csv")#文件路径

In [36]:
# D:\records_singleArray.json

filename_records_singleArray=r"D:\records_singleArray.json"

pyspark 读取 json

In [42]:
readJSONDF = spark.read.json(filename_records_singleArray)

In [41]:
readJSONDF.show()

AnalysisException:
Since Spark 2.3, the queries from raw JSON/CSV files are disallowed when the
referenced columns only include the internal corrupt record column
(named _corrupt_record by default). For example:
spark.read.schema(schema).csv(file).filter($"_corrupt_record".isNotNull).count()
and spark.read.schema(schema).csv(file).select("_corrupt_record").show().
Instead, you can cache or save the parsed results and then send the same query.
For example, val df = spark.read.schema(schema).csv(file).cache() and then
df.filter($"_corrupt_record".isNotNull).count().

In [43]:
readJSONDF.toPandas()

   answer  choice1  difficulty  id  pointId  score  type  userId
0      31  choise3        10.0   0        8    2.0     1       0
1      31  choise3         4.0   0        6    2.0     1       0
2      31  choise3        10.0   0        8    2.0     1       0
3      31  choise3         3.0   0       10    2.0     1       0
4      31  choise3        10.0   0        8    2.0     1       0
5      31  choise3         3.0   0       10    2.0     1       0
6      31  choise3         4.0   0        6    2.0     1       0
7      31  choise3        10.0   0        8    2.0     1       0
8      31  choise3        10.0   0        8    2.0     1       0
9      31  choise3        10.0   0        8    2.0     1       0
10     31  choise3         3.0   0        1    2.0     1       0
11     31  choise3         4.0   0        6    2.0     1       0
12     31  choise3        10.0   0        8    2.0     1       0
13     31  choise3         3.0   0        1    2.0     1       0
14     31  choise3         7.0   0        9    2.0     1       0
15     31  choise3        10.0   0        8    2.0     1       0
16     31  choise3         3.0   0       10    2.0     1       0
17     31  choise3         3.0   0        1    2.0     1       0
18     31  choise3         3.0   0       10    2.0     1       0
19     31  choise3         3.0   0        1    2.0     1       0
20     31  choise3         4.0   0        6    2.0     1       0
21     31  choise3        10.0   0        8    2.0     1       0
22     31  choise3        10.0   0        8    2.0     1       0
23     31  choise3        10.0   0        8    2.0     1       0
24     31  choise3         4.0   0        6    2.0     1       0
25     31  choise3         3.0   0        1    2.0     1       0
26     31  choise3        10.0   0        8    2.0     1       0
27     31  choise3         4.0   0        6    2.0     1       0
28     31  choise3         4.0   0        6    2.0     1       0
29     31  choise3        10.0   0        8    2.0     1       0
30     31  choise3         3.0   0        1    2.0     1       0